# Utiliser Node.js 20 comme base
FROM node:20

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de configuration (package.json et package-lock.json)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port utilisé par Vite (par défaut 5173)
EXPOSE 8080

# Lancer le serveur Vite
CMD ["npm", "run", "dev"]
